disabled and enabled buttons module-3 task-1
js-tasks-ru/htmlcss-20220519_alexdolzenko pull request #3
Opened 2022-05-25 20:28 UTC by Elbrain

2022-05-25 20:28 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-05-26 14:55 UTC, GSemikozov requested changes

2022-05-26 14:55 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +@import '../../assets/css/main.css';
импортировать не нужно, подключаем глобально

2022-05-26 14:55 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +:root {
root селектор у нас уже определен там, где нужно определять глобальные стили)
нужно унести туда.

2022-05-26 14:55 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    width: 189px;
ширину лучше жестко не фиксировать, простой кейс когда ломается верстка - очень длинный текст

2022-05-26 14:55 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    margin: 10px;
марджины на уровне блока не задаем

2022-05-26 14:55 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    font-style: normal;
не хватает font-family

2022-05-26 14:55 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    margin: 10px;
а вот внутренних отступов как раз и не хватает

2022-06-05 17:50 UTC, GSemikozov approved these changes

2022-06-05 17:50 UTC, merged